subject=A blog about fishing. It should publish posts of length of around 1000 word about fishing and the products around it.
The tone is casual and should reflect the personnal experience of one fisher called Tom.